# Expanded NHANES elevated-HbA1c classification experiment

This standalone research notebook evaluates whether verified diet, background,
and contextual variables add predictive information beyond WellPath-style KPIs.

**Outcome:** `elevated_hba1c = 1` when measured HbA1c is at least 5.7%, otherwise
0. This is a cross-sectional classification target—not a diagnosis of diabetes,
not a prediction of future diabetes, and not a clinically validated tool.

The analysis uses only the files in `data/raw/nhanes/`. It never invents missing
variables and never uses WellPath application users for model performance.

## Design and safeguards

- One participant row per `SEQN`; joins are validated one-to-one.
- Stratified 80/20 train/test splits with `random_state=42`.
- Five-fold stratified cross-validation occurs only inside training data.
- Imputation, scaling, and one-hot encoding are fitted inside sklearn pipelines.
- Direct target fields, glucose, diagnoses, medications, and insulin are forbidden.
- The strict complete-case comparison requires every experiment predictor.
- A separate shared cohort compares KPI + demographics, diet, the combined
  medical/family-risk proxy, and the shared full model without unrelated groups.
- Available-case models require at least 60% of their own predictors to be
  observed before training-only imputation.
- Direct incremental comparisons use identical held-out participants.
- Confidence intervals use 1,000 fixed-seed bootstrap resamples.
- Diet recalls are one or two 24-hour snapshots, not perfect usual-diet measures.

Official wording was checked against the CDC/NCHS 2017–2018 component codebooks
for DIQ_J, DBQ_J, DR1TOT_J, and DR2TOT_J.

In [1]:
from pathlib import Path
import sys
from IPython.display import Markdown, display

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.expanded_analysis import run_expanded_analysis

results = run_expanded_analysis(PROJECT_ROOT)
summary = results["summary"]
print("Expanded analysis completed.")
print(summary)

Expanded analysis completed.
{'eligible_participants': 6045, 'positive_participants': 2386, 'negative_participants': 3659, 'diet_variables_found': ['diet_calories', 'diet_carbohydrate_g', 'diet_total_sugar_g', 'diet_fiber_g', 'diet_protein_g', 'diet_total_fat_g', 'diet_saturated_fat_g', 'diet_sodium_mg', 'diet_potassium_mg', 'diet_cholesterol_mg', 'diet_alcohol_g', 'meals_away_from_home_7d', 'fast_food_meals_7d', 'ready_to_eat_meals_30d', 'frozen_meals_30d', 'self_rated_diet_quality'], 'family_history_status': 'Combined medical/family-risk proxy found', 'smoking_variables_found': [], 'food_security_variables_found': [], 'healthcare_access_variables_found': [], 'models_successfully_trained': 35, 'available_case_min_predictor_fraction': 0.6, 'complete_case_sample_size': 2713, 'shared_comparison_sample_size': 2713, 'available_case_full_model_sample_size': 5671, 'best_complete_case_model': 'Model 14: Full with BMI only', 'best_complete_case_estimator': 'Regularized logistic regression', 'best_complete_case_roc_auc': 0.7834274663883602, 'best_available_case_model': 'Model 6: + all verified diet', 'best_available_case_estimator': 'Regularized logistic regression', 'best_available_case_roc_auc': 0.8035936223855689, 'diet_incremental_result': 'No clear meaningful improvement; gain is small and/or uncertainty includes no improvement', 'diet_delta_roc_auc': 0.004573638651851009, 'diet_delta_roc_auc_ci_lower': -0.009079539350167583, 'diet_delta_roc_auc_ci_upper': 0.01795030178442833, 'proxy_incremental_result': 'No clear meaningful improvement; gain is small and/or uncertainty includes no improvement', 'proxy_delta_roc_auc': 0.00532567990668531, 'proxy_delta_roc_auc_ci_lower': -0.0013429656386033662, 'proxy_delta_roc_auc_ci_upper': 0.01224793914581781, 'full_vs_age_bmi_result': 'No clear meaningful improvement; gain is small and/or uncertainty includes no improvement', 'full_vs_age_bmi_delta_roc_auc': 0.018785683590152757, 'full_vs_age_bmi_delta_roc_auc_ci_lower': -0.0017808838577344248, 'full_vs_age_bmi_delta_roc_auc_ci_upper': 0.03839531690534858, 'weight_beyond_bmi_result': 'No clear meaningful improvement; gain is small and/or uncertainty includes no improvement', 'weight_beyond_bmi_delta_roc_auc': -0.0024096015716127406, 'weight_beyond_bmi_delta_roc_auc_ci_lower': -0.006961725281885733, 'weight_beyond_bmi_delta_roc_auc_ci_upper': 0.0029808445021063472, 'safety': 'Exploratory elevated-HbA1c classification research prototype; not diagnostic or clinically validated.'}

## 1. NHANES file inventory

In [2]:
inventory = results["inventory"]
display(inventory.groupby("filename", as_index=False).agg(
    rows=("number_of_rows", "first"),
    columns=("number_of_columns", "first"),
    seqn_exists=("seqn_exists", "first"),
    status=("status", "first"),
))
print(f"Full inventory rows (one per source column): {len(inventory):,}")
display(inventory.head(20))

        filename  rows  columns  seqn_exists  status
0      BMX_J.xpt  8704       21         True  loaded
1      BPX_J.xpt  8704       21         True  loaded
2      DBQ_J.xpt  9254       46         True  loaded
3     DEMO_J.xpt  9254       46         True  loaded
4      DIQ_J.xpt  8897       54         True  loaded
5   DR1TOT_J.xpt  8704      168         True  loaded
6   DR2TOT_J.xpt  8704       85         True  loaded
7      GHB_J.xpt  6401        2         True  loaded
8      OCQ_J.xpt  6161       10         True  loaded
9      PAQ_J.xpt  5856       17         True  loaded
10     SLQ_J.xpt  6161       11         True  loaded

Full inventory rows (one per source column): 481

,filename,number_of_rows,number_of_columns,seqn_exists,all_column_names,column_name,column_dtype,status,message
0,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,SEQN,float64,loaded,
1,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMDSTATS,float64,loaded,
2,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXWT,float64,loaded,
3,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIWT,float64,loaded,
4,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXRECUM,float64,loaded,
5,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIRECUM,float64,loaded,
6,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXHEAD,float64,loaded,
7,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIHEAD,float64,loaded,
8,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXHT,float64,loaded,
9,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIHT,float64,loaded,
10,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXBMI,float64,loaded,
11,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXLEG,float64,loaded,
12,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMILEG,float64,loaded,
13,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXARML,float64,loaded,
14,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIARML,float64,loaded,
15,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXARMC,float64,loaded,
16,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIARMC,float64,loaded,
17,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXWAIST,float64,loaded,
18,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMIWAIST,float64,loaded,
19,BMX_J.xpt,8704,21,True,SEQN; BMDSTATS; BMXWT; BMIWT; BMXRECUM; BMIREC...,BMXHIP,float64,loaded,

The full machine-readable inventory includes every column name and dtype
and is saved as `outputs/tables/nhanes_file_inventory.csv`.

## 2. Variable discovery

In [3]:
display(results["discovery"])
print("Verified feature groups:")
for group, fields in results["groups"].items():
    print(f"- {group}: {fields if fields else 'none available'}")

,requested_concept,participant_feature,source_day,matching_source_file,matching_variable_code,variable_label,response_coding,missing_value_codes,decision,concept_available,notes
0,Calories,diet_calories,day 1,DR1TOT_J,DR1TKCAL,Energy (kcal),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
1,Calories,diet_calories,day 2,DR2TOT_J,DR2TKCAL,Energy (kcal),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
2,Carbohydrate,diet_carbohydrate_g,day 1,DR1TOT_J,DR1TCARB,Carbohydrate (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
3,Carbohydrate,diet_carbohydrate_g,day 2,DR2TOT_J,DR2TCARB,Carbohydrate (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
4,Total Sugar,diet_total_sugar_g,day 1,DR1TOT_J,DR1TSUGR,Total sugars (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
5,Total Sugar,diet_total_sugar_g,day 2,DR2TOT_J,DR2TSUGR,Total sugars (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
6,Fiber,diet_fiber_g,day 1,DR1TOT_J,DR1TFIBE,Dietary fiber (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
7,Fiber,diet_fiber_g,day 2,DR2TOT_J,DR2TFIBE,Dietary fiber (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
8,Protein,diet_protein_g,day 1,DR1TOT_J,DR1TPROT,Protein (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
9,Protein,diet_protein_g,day 2,DR2TOT_J,DR2TPROT,Protein (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
10,Total Fat,diet_total_fat_g,day 1,DR1TOT_J,DR1TTFAT,Total fat (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
11,Total Fat,diet_total_fat_g,day 2,DR2TOT_J,DR2TTFAT,Total fat (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
12,Saturated Fat,diet_saturated_fat_g,day 1,DR1TOT_J,DR1TSFAT,Total saturated fatty acids (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
13,Saturated Fat,diet_saturated_fat_g,day 2,DR2TOT_J,DR2TSFAT,Total saturated fatty acids (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
14,Sodium,diet_sodium_mg,day 1,DR1TOT_J,DR1TSODI,Sodium (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
15,Sodium,diet_sodium_mg,day 2,DR2TOT_J,DR2TSODI,Sodium (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
16,Potassium,diet_potassium_mg,day 1,DR1TOT_J,DR1TPOTA,Potassium (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
17,Potassium,diet_potassium_mg,day 2,DR2TOT_J,DR2TPOTA,Potassium (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
18,Cholesterol,diet_cholesterol_mg,day 1,DR1TOT_J,DR1TCHOL,Cholesterol (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
19,Cholesterol,diet_cholesterol_mg,day 2,DR2TOT_J,DR2TCHOL,Cholesterol (mg),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
20,Alcohol,diet_alcohol_g,day 1,DR1TOT_J,DR1TALCO,Alcohol (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
21,Alcohol,diet_alcohol_g,day 2,DR2TOT_J,DR2TALCO,Alcohol (gm),Continuous daily intake; participant feature a...,. = missing,usable,True,Source column loaded. One or two 24-hour recal...
22,Added sugars,NaN,NaN,,,,,,unavailable,NaN,No verified added-sugars total was found in th...
23,Meals Away From Home 7D,NaN,NaN,DBQ_J,DBD895,# of meals not home prepared,0-21 meals; 5555 means more than 21 and is set...,7777/9999; structural missing,usable,NaN,Official 2017-2018 NHANES codebook wording.
24,Fast Food Meals 7D,NaN,NaN,DBQ_J,DBD900,# of meals from fast food or pizza place,0-21 meals; 5555 means more than 21 and is set...,7777/9999; structural missing,usable,NaN,Official 2017-2018 NHANES codebook wording.
25,Ready To Eat Meals 30D,NaN,NaN,DBQ_J,DBD905,# of ready-to-eat foods in past 30 days,0-90 times; 6666 means more than 90 and is set...,7777/9999; structural missing,usable,NaN,Official 2017-2018 NHANES codebook wording.
26,Frozen Meals 30D,NaN,NaN,DBQ_J,DBD910,# of frozen meals/pizza in past 30 days,0-90 times; 6666 means more than 90 and is set...,7777/9999; structural missing,usable,NaN,Official 2017-2018 NHANES codebook wording.
27,Self Rated Diet Quality,NaN,NaN,DBQ_J,DBQ700,How healthy is the diet,"1 Excellent, 2 Very good, 3 Good, 4 Fair, 5 Poor",7 refused; 9 don't know; structural missing,usable,NaN,Official 2017-2018 NHANES codebook wording.
28,Family history of diabetes,NaN,NaN,DIQ_J,DIQ175A,Family history,10 = selected; 99 = don't know,99; structural skip,ambiguous,NaN,Asked only among people who said they felt at ...
29,Parent with diabetes,NaN,NaN,,,,,,unavailable,NaN,No defensible field was found in the loaded co...
30,Sibling with diabetes,NaN,NaN,,,,,,unavailable,NaN,No defensible field was found in the loaded co...
31,Family history of heart disease,NaN,NaN,,,,,,unavailable,NaN,No defensible field was found in the loaded co...
32,Family history of hypertension,NaN,NaN,,,,,,unavailable,NaN,No defensible field was found in the loaded co...
33,Medical or family-history risk for diabetes,NaN,NaN,DIQ_J,DIQ170,Ever told have health risk for diabetes,1 yes; 2 no,7 refused; 9 don't know; structural missing,usable,NaN,Combined medical/family-risk proxy; it is not ...
34,Current smoker,NaN,NaN,,,,,,unavailable,NaN,SMQ_J is not present; no unrelated substitute ...
35,Former smoker,NaN,NaN,,,,,,unavailable,NaN,SMQ_J is not present; no unrelated substitute ...
36,Never smoker,NaN,NaN,,,,,,unavailable,NaN,SMQ_J is not present; no unrelated substitute ...
37,Cigarettes per day,NaN,NaN,,,,,,unavailable,NaN,SMQ_J is not present; no unrelated substitute ...
38,Years smoked,NaN,NaN,,,,,,unavailable,NaN,SMQ_J is not present; no unrelated substitute ...
39,Household food-security category,NaN,NaN,,,,,,unavailable,NaN,FSQ_J is not present; no unrelated substitute ...
40,Worry about food running out,NaN,NaN,,,,,,unavailable,NaN,FSQ_J is not present; no unrelated substitute ...
41,Food not lasting,NaN,NaN,,,,,,unavailable,NaN,FSQ_J is not present; no unrelated substitute ...
42,Reduced meals,NaN,NaN,,,,,,unavailable,NaN,FSQ_J is not present; no unrelated substitute ...
43,Unable to afford balanced meals,NaN,NaN,,,,,,unavailable,NaN,FSQ_J is not present; no unrelated substitute ...
44,Has a regular healthcare location,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...
45,Has a regular healthcare provider,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...
46,Time since last healthcare visit,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...
47,Health insurance,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...
48,Delayed care,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...
49,Could not afford care,NaN,NaN,,,,,,unavailable,NaN,HUQ_J/health-insurance components are not pres...

Verified feature groups:
- core_kpis: ['sleep_hours', 'resting_heart_rate', 'systolic_bp', 'diastolic_bp', 'bmi', 'weight_kg', 'vigorous_activity', 'moderate_activity', 'sedentary_minutes']
- demographics: ['age', 'sex', 'income_context']
- diet_nutrients: ['diet_calories', 'diet_carbohydrate_g', 'diet_total_sugar_g', 'diet_fiber_g', 'diet_protein_g', 'diet_total_fat_g', 'diet_saturated_fat_g', 'diet_sodium_mg', 'diet_potassium_mg', 'diet_cholesterol_mg', 'diet_alcohol_g']
- diet_behaviours: ['meals_away_from_home_7d', 'fast_food_meals_7d', 'ready_to_eat_meals_30d', 'frozen_meals_30d', 'self_rated_diet_quality']
- family_history: none available
- medical_family_risk_proxy: ['medical_or_family_diabetes_risk']
- smoking: none available
- food_security: none available
- healthcare_access: none available

## 3. Family-history wording review

In [4]:
display(results["family_review"])
display(Markdown(
    "**Selected status:** " + summary["family_history_status"] +
    "\n\nDIQ175A is not used as a universal family-history predictor because it "
    "is asked only as a reason for perceived risk. DIQ170 is used only as the "
    "combined `medical_or_family_diabetes_risk` proxy and is never described as "
    "genetics or pure family history."
))

,selected_status,candidate_variable,official_wording,assessment,reason,selected_for_model
0,Combined medical/family-risk proxy found,DIQ175A,Why do you think you are at risk for diabetes ...,Ambiguous / not suitable as a universal family...,"Asked only after reported perceived risk; 7,75...",False
1,Combined medical/family-risk proxy found,DIQ170,Ever told by a health professional of health c...,Combined medical/family-risk proxy found,The wording combines medical conditions and fa...,True
2,Combined medical/family-risk proxy found,MCQ_J and other questionnaire files,No direct universal family-history field found...,No direct family-history variable found,MCQ_J is absent and no participant diagnosis w...,False

**Selected status:** Combined medical/family-risk proxy found

DIQ175A is not used as a universal family-history predictor because it is asked only as a reason for perceived risk. DIQ170 is used only as the combined `medical_or_family_diabetes_risk` proxy and is never described as genetics or pure family history.

## 4. Diet engineering

In [5]:
display(Markdown(
    "**Verified diet variables:** " + ", ".join(summary["diet_variables_found"]) +
    "\n\nFor nutrients, the participant value is the mean of day 1 and day 2 "
    "when both exist, day 1 when day 2 is missing, and missing when both are "
    "missing. `diet_recall_days_available` records whether one or two days were used."
))
display(results["diet_unadjusted"].head(20))
display(results["diet_adjusted"].head(20))

**Verified diet variables:** diet_calories, diet_carbohydrate_g, diet_total_sugar_g, diet_fiber_g, diet_protein_g, diet_total_fat_g, diet_saturated_fat_g, diet_sodium_mg, diet_potassium_mg, diet_cholesterol_mg, diet_alcohol_g, meals_away_from_home_7d, fast_food_meals_7d, ready_to_eat_meals_30d, frozen_meals_30d, self_rated_diet_quality

For nutrients, the participant value is the mean of day 1 and day 2 when both exist, day 1 when day 2 is missing, and missing when both are missing. `diet_recall_days_available` records whether one or two days were used.

,variable,participants,effect_scale,odds_ratio,odds_ratio_per_1_sd,odds_ratio_yes_vs_no,ci_lower,ci_upper,p_value,elevated_group_median,non_elevated_group_median,missing_percent,interpretation
0,diet_calories,5523,Per 1 standard deviation,0.929615,0.929615,NaN,0.879999,0.982028,9.107629e-03,1.843000e+03,1.887500e+03,8.635236,"Exploratory association, not a causal effect"
1,diet_carbohydrate_g,5523,Per 1 standard deviation,0.926684,0.926684,NaN,0.877105,0.979065,6.645294e-03,2.184525e+02,2.260850e+02,8.635236,"Exploratory association, not a causal effect"
2,diet_total_sugar_g,5523,Per 1 standard deviation,0.917133,0.917133,NaN,0.867382,0.969739,2.367226e-03,8.556500e+01,9.111000e+01,8.635236,"Exploratory association, not a causal effect"
3,diet_fiber_g,5523,Per 1 standard deviation,1.089463,1.089463,NaN,1.032567,1.149493,1.741877e-03,1.485000e+01,1.385000e+01,8.635236,"Exploratory association, not a causal effect"
4,diet_protein_g,5523,Per 1 standard deviation,0.968627,0.968627,NaN,0.917361,1.022757,2.505945e-01,7.135750e+01,7.090500e+01,8.635236,"Exploratory association, not a causal effect"
5,diet_total_fat_g,5523,Per 1 standard deviation,1.000999,1.000999,NaN,0.948314,1.056611,9.711345e-01,7.432250e+01,7.474500e+01,8.635236,"Exploratory association, not a causal effect"
6,diet_saturated_fat_g,5523,Per 1 standard deviation,0.954107,0.954107,NaN,0.903394,1.007667,9.181694e-02,2.329650e+01,2.394550e+01,8.635236,"Exploratory association, not a causal effect"
7,diet_sodium_mg,5523,Per 1 standard deviation,0.955648,0.955648,NaN,0.904765,1.009392,1.041447e-01,3.012750e+03,3.084500e+03,8.635236,"Exploratory association, not a causal effect"
8,diet_potassium_mg,5523,Per 1 standard deviation,1.055021,1.055021,NaN,0.999745,1.113353,5.109421e-02,2.340250e+03,2.234000e+03,8.635236,"Exploratory association, not a causal effect"
9,diet_cholesterol_mg,5523,Per 1 standard deviation,1.084696,1.084696,NaN,1.028060,1.144451,2.964597e-03,2.585000e+02,2.390000e+02,8.635236,"Exploratory association, not a causal effect"
10,diet_alcohol_g,5523,Per 1 standard deviation,0.807301,0.807301,NaN,0.750486,0.868418,8.972001e-09,5.397605e-79,5.397605e-79,8.635236,"Exploratory association, not a causal effect"
11,meals_away_from_home_7d,6011,Per 1 standard deviation,0.855522,0.855522,NaN,0.809821,0.903802,2.532476e-08,2.000000e+00,2.000000e+00,0.562448,"Exploratory association, not a causal effect"
12,fast_food_meals_7d,4677,Per 1 standard deviation,0.896674,0.896674,NaN,0.842340,0.954512,6.268793e-04,1.000000e+00,1.000000e+00,22.630273,"Exploratory association, not a causal effect"
13,ready_to_eat_meals_30d,6005,Per 1 standard deviation,0.892123,0.892123,NaN,0.841283,0.946034,1.372303e-04,0.000000e+00,0.000000e+00,0.661704,"Exploratory association, not a causal effect"
14,frozen_meals_30d,6015,Per 1 standard deviation,0.881837,0.881837,NaN,0.830842,0.935961,3.510248e-05,0.000000e+00,0.000000e+00,0.496278,"Exploratory association, not a causal effect"
15,self_rated_diet_quality,5538,Per 1 standard deviation,1.042571,1.042571,NaN,0.988373,1.099742,1.258712e-01,3.000000e+00,3.000000e+00,8.387097,"Exploratory association, not a causal effect"

,variable,participants,effect_scale,odds_ratio,odds_ratio_per_1_sd,odds_ratio_yes_vs_no,ci_lower,ci_upper,p_value,elevated_group_median,non_elevated_group_median,missing_percent,interpretation
0,diet_calories,4729,Per 1 standard deviation,0.974129,0.974129,NaN,0.906734,1.046533,4.736365e-01,1.843000e+03,1.887500e+03,8.635236,"Exploratory association, not a causal effect"
1,diet_carbohydrate_g,4729,Per 1 standard deviation,1.021393,1.021393,NaN,0.953149,1.094523,5.485447e-01,2.184525e+02,2.260850e+02,8.635236,"Exploratory association, not a causal effect"
2,diet_total_sugar_g,4729,Per 1 standard deviation,0.964000,0.964000,NaN,0.901479,1.030857,2.838663e-01,8.556500e+01,9.111000e+01,8.635236,"Exploratory association, not a causal effect"
3,diet_fiber_g,4729,Per 1 standard deviation,1.056831,1.056831,NaN,0.988865,1.129468,1.031423e-01,1.485000e+01,1.385000e+01,8.635236,"Exploratory association, not a causal effect"
4,diet_protein_g,4729,Per 1 standard deviation,0.991549,0.991549,NaN,0.922867,1.065342,8.167520e-01,7.135750e+01,7.090500e+01,8.635236,"Exploratory association, not a causal effect"
5,diet_total_fat_g,4729,Per 1 standard deviation,1.020812,1.020812,NaN,0.952192,1.094377,5.618058e-01,7.432250e+01,7.474500e+01,8.635236,"Exploratory association, not a causal effect"
6,diet_saturated_fat_g,4729,Per 1 standard deviation,0.975512,0.975512,NaN,0.909919,1.045833,4.851032e-01,2.329650e+01,2.394550e+01,8.635236,"Exploratory association, not a causal effect"
7,diet_sodium_mg,4729,Per 1 standard deviation,1.020654,1.020654,NaN,0.950240,1.096285,5.751206e-01,3.012750e+03,3.084500e+03,8.635236,"Exploratory association, not a causal effect"
8,diet_potassium_mg,4729,Per 1 standard deviation,0.952126,0.952126,NaN,0.888572,1.020226,1.639718e-01,2.340250e+03,2.234000e+03,8.635236,"Exploratory association, not a causal effect"
9,diet_cholesterol_mg,4729,Per 1 standard deviation,1.017716,1.017716,NaN,0.949855,1.090425,6.179417e-01,2.585000e+02,2.390000e+02,8.635236,"Exploratory association, not a causal effect"
10,diet_alcohol_g,4729,Per 1 standard deviation,0.723800,0.723800,NaN,0.660053,0.793705,6.346571e-12,5.397605e-79,5.397605e-79,8.635236,"Exploratory association, not a causal effect"
11,meals_away_from_home_7d,5162,Per 1 standard deviation,0.960781,0.960781,NaN,0.898255,1.027659,2.438972e-01,2.000000e+00,2.000000e+00,0.562448,"Exploratory association, not a causal effect"
12,fast_food_meals_7d,4031,Per 1 standard deviation,1.034227,1.034227,NaN,0.958551,1.115878,3.853618e-01,1.000000e+00,1.000000e+00,22.630273,"Exploratory association, not a causal effect"
13,ready_to_eat_meals_30d,5162,Per 1 standard deviation,0.902600,0.902600,NaN,0.840385,0.969421,4.919643e-03,0.000000e+00,0.000000e+00,0.661704,"Exploratory association, not a causal effect"
14,frozen_meals_30d,5165,Per 1 standard deviation,0.916117,0.916117,NaN,0.858020,0.978148,8.769572e-03,0.000000e+00,0.000000e+00,0.496278,"Exploratory association, not a causal effect"
15,self_rated_diet_quality,5172,Per 1 standard deviation,1.111648,1.111648,NaN,1.041097,1.186980,1.556943e-03,3.000000e+00,3.000000e+00,8.387097,"Exploratory association, not a causal effect"

## 5. Leakage audit

In [6]:
audit = results["audit"]
display(audit)
assert audit["allowed"].all()
print("PASS: no forbidden target or direct-proxy field appears among predictors.")

,model,predictor,matched_forbidden_terms,direct_target_or_proxy,allowed,review_note
0,Model 0: Age only,age,,False,True,Passed name-based audit
1,Model 1: Age + BMI,age,,False,True,Passed name-based audit
2,Model 1: Age + BMI,bmi,,False,True,Passed name-based audit
3,Baseline 3: Age + BMI + systolic BP,age,,False,True,Passed name-based audit
4,Baseline 3: Age + BMI + systolic BP,bmi,,False,True,Passed name-based audit
...,...,...,...,...,...,...
201,Model 14: Full with BMI only,fast_food_meals_7d,,False,True,Passed name-based audit
202,Model 14: Full with BMI only,ready_to_eat_meals_30d,,False,True,Passed name-based audit
203,Model 14: Full with BMI only,frozen_meals_30d,,False,True,Passed name-based audit
204,Model 14: Full with BMI only,self_rated_diet_quality,,False,True,Passed name-based audit
205,Model 14: Full with BMI only,medical_or_family_diabetes_risk,,False,True,Passed name-based audit

PASS: no forbidden target or direct-proxy field appears among predictors.

## 6. Strict, shared-cohort, and available-case model comparisons

In [7]:
comparison = results["comparison"]
display(results["cohort_report"])
display(comparison.sort_values(["comparison", "roc_auc"], ascending=[True, False]))
display(results["sample_size"])
display(results["integrity_audit"])
assert results["integrity_audit"]["training_only_preprocessing"].all()
assert results["integrity_audit"]["untouched_held_out_test_set"].all()
assert results["integrity_audit"]["no_hba1c_or_diagnosis_leakage"].all()
print("PASS: training-only pipelines, untouched tests, leakage controls, and paired participant checks verified.")

,cohort,participant_count,predictor_scope,minimum_predictor_fraction,required_nonmissing_predictors,notes
0,Strict complete-case,2713,age; bmi; systolic_bp; sleep_hours; resting_he...,1.0,29,Used for the global complete-case comparison.
1,Shared-comparison,2713,sleep_hours; resting_heart_rate; systolic_bp; ...,1.0,29,"Used only for KPI + demographics, diet, proxy,..."
2,Available-case full model,5671,sleep_hours; resting_heart_rate; systolic_bp; ...,0.6,18,Eligibility checked before training-only imput...

,comparison,model,estimator,features,number_of_participants,positive_class_prevalence,training_count,test_count,cv_roc_auc_training_only,best_parameters,...,brier_score,roc_auc_ci_lower,roc_auc_ci_upper,pr_auc_ci_lower,pr_auc_ci_upper,recall_ci_lower,recall_ci_upper,specificity_ci_lower,specificity_ci_upper,bootstrap_resamples
15,Available-case,Model 6: + all verified diet,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5696,0.392205,4556,1140,0.800949,"{""model__C"": 1.0}",...,0.182364,0.776462,0.828321,0.636929,0.732593,0.752735,0.828198,0.675244,0.745434,1000
23,Available-case,Model 13: Full without family/proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5696,0.392205,4556,1140,0.800949,"{""model__C"": 1.0}",...,0.182364,0.776874,0.829008,0.637635,0.730311,0.753473,0.828644,0.678733,0.743592,1000
5,Available-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,age; bmi; systolic_bp,5966,0.397251,4772,1194,0.788088,"{""model__C"": 1.0}",...,0.180894,0.774614,0.823136,0.651612,0.735515,0.674363,0.756774,0.728511,0.792374,1000
33,Available-case,Model 11: Full verified,Gradient boosting,sleep_hours; resting_heart_rate; systolic_bp; ...,5671,0.389526,4536,1135,0.812078,{},...,0.178540,0.766789,0.819278,0.642482,0.736593,0.604750,0.693880,0.750742,0.813033,1000
13,Available-case,Model 5: + diet behaviours,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5809,0.407299,4647,1162,0.788887,"{""model__C"": 1.0}",...,0.184371,0.766665,0.820051,0.651229,0.738101,0.702759,0.778689,0.702243,0.767735,1000
32,Available-case,Model 11: Full verified,Random forest,sleep_hours; resting_heart_rate; systolic_bp; ...,5671,0.389526,4536,1135,0.811961,{},...,0.185386,0.762193,0.814678,0.635522,0.724511,0.685013,0.772730,0.676214,0.743188,1000
25,Available-case,Model 14: Full with BMI only,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5672,0.389457,4537,1135,0.805132,"{""model__C"": 1.0}",...,0.187751,0.759430,0.812473,0.606336,0.704663,0.698661,0.785714,0.698322,0.764539,1000
19,Available-case,Model 11: Full verified,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5671,0.389526,4536,1135,0.805254,"{""model__C"": 1.0}",...,0.188747,0.759436,0.810151,0.621722,0.709397,0.707560,0.783302,0.686211,0.752959,1000
11,Available-case,Model 4: + diet nutrients,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5521,0.390147,4416,1105,0.802799,"{""model__C"": 1.0}",...,0.190428,0.755666,0.809354,0.614887,0.710980,0.686921,0.769741,0.679758,0.745849,1000
9,Available-case,Model 3: Core KPIs + demographics,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5474,0.424735,4379,1095,0.788903,"{""model__C"": 1.0}",...,0.195244,0.741597,0.798494,0.624774,0.719271,0.690570,0.771194,0.647252,0.715258,1000
3,Available-case,Model 1: Age + BMI,Regularized logistic regression,age; bmi,5173,0.438237,4138,1035,0.780461,"{""model__C"": 1.0}",...,0.195267,0.737915,0.795853,0.638783,0.732746,0.686654,0.769414,0.641281,0.715049,1000
1,Available-case,Model 0: Age only,Regularized logistic regression,age,5261,0.439080,4208,1053,0.746104,"{""model__C"": 1.0}",...,0.198932,0.731474,0.788610,0.607142,0.705129,0.665245,0.747325,0.625413,0.704896,1000
17,Available-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5918,0.400135,4734,1184,0.800555,"{""model__C"": 1.0}",...,0.200169,0.731615,0.786685,0.571846,0.666614,0.678345,0.758409,0.657508,0.726352,1000
21,Available-case,Model 12: Full without diet,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5918,0.400135,4734,1184,0.800555,"{""model__C"": 1.0}",...,0.200169,0.731092,0.783595,0.569042,0.666599,0.677963,0.758912,0.660373,0.725627,1000
7,Available-case,Model 2: Core KPIs,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,5494,0.423189,4395,1099,0.709118,"{""model__C"": 1.0}",...,0.202625,0.726135,0.782890,0.631365,0.720164,0.596946,0.689521,0.694617,0.765799,1000
24,Complete-case,Model 14: Full with BMI only,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.771221,"{""model__C"": 1.0}",...,0.188241,0.744418,0.824749,0.526236,0.682766,0.655914,0.784539,0.666644,0.762046,1000
18,Complete-case,Model 11: Full verified,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.772701,"{""model__C"": 1.0}",...,0.189328,0.739292,0.820560,0.516313,0.672209,0.643569,0.774894,0.661387,0.760753,1000
31,Complete-case,Model 11: Full verified,Gradient boosting,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.765936,{},...,0.175224,0.743854,0.819733,0.545388,0.692981,0.426131,0.574303,0.823366,0.892862,1000
16,Complete-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.771879,"{""model__C"": 1.0}",...,0.192270,0.736076,0.817161,0.508137,0.664029,0.624364,0.755838,0.656727,0.754055,1000
20,Complete-case,Model 12: Full without diet,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.771879,"{""model__C"": 1.0}",...,0.192270,0.741863,0.811796,0.512711,0.658891,0.626250,0.763752,0.658720,0.752610,1000
14,Complete-case,Model 6: + all verified diet,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.770855,"{""model__C"": 1.0}",...,0.192192,0.734032,0.815411,0.515683,0.671687,0.644556,0.782642,0.663156,0.753389,1000
22,Complete-case,Model 13: Full without family/proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.770855,"{""model__C"": 1.0}",...,0.192192,0.737323,0.815406,0.513353,0.671776,0.646699,0.783138,0.664020,0.753972,1000
10,Complete-case,Model 4: + diet nutrients,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.773369,"{""model__C"": 1.0}",...,0.192501,0.734658,0.814472,0.525068,0.668535,0.635415,0.771441,0.661876,0.755321,1000
30,Complete-case,Model 11: Full verified,Random forest,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.758071,{},...,0.186622,0.734589,0.811073,0.530979,0.679607,0.608240,0.740752,0.658179,0.749343,1000
12,Complete-case,Model 5: + diet behaviours,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.766424,"{""model__C"": 1.0}",...,0.194520,0.732888,0.810425,0.507894,0.656725,0.624944,0.759036,0.657141,0.751368,1000
8,Complete-case,Model 3: Core KPIs + demographics,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.769476,"{""model__C"": 1.0}",...,0.194897,0.734124,0.808487,0.501828,0.655235,0.636312,0.775284,0.658711,0.750000,1000
4,Complete-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,age; bmi; systolic_bp,2713,0.329525,2170,543,0.766448,"{""model__C"": 1.0}",...,0.200021,0.727984,0.800882,0.504050,0.651176,0.603738,0.740974,0.645494,0.740957,1000
2,Complete-case,Model 1: Age + BMI,Regularized logistic regression,age; bmi,2713,0.329525,2170,543,0.761834,"{""model__C"": 1.0}",...,0.198874,0.722919,0.800580,0.495761,0.646359,0.599973,0.737980,0.630244,0.727291,1000
0,Complete-case,Model 0: Age only,Regularized logistic regression,age,2713,0.329525,2170,543,0.736450,"{""model__C"": 1.0}",...,0.205508,0.697982,0.781020,0.457127,0.598979,0.610525,0.750032,0.657963,0.752757,1000
6,Complete-case,Model 2: Core KPIs,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.702160,"{""model__C"": 1.0}",...,0.219061,0.672132,0.762022,0.442726,0.591524,0.608967,0.742861,0.634003,0.730881,1000
34,Complete-case,Sanity check: prior dummy,Dummy classifier,,2713,0.329525,2170,543,0.500000,{},...,0.220981,0.500000,0.500000,0.282494,0.398309,0.000000,0.000000,1.000000,1.000000,1000
29,Shared-comparison,Shared full: KPIs + demographics + diet + proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.772701,"{""model__C"": 1.0}",...,0.189328,0.741845,0.819470,0.515909,0.674700,0.638874,0.779883,0.659319,0.754904,1000
28,Shared-comparison,Model 7P: + medical/family-risk proxy,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.771879,"{""model__C"": 1.0}",...,0.192270,0.739161,0.814786,0.515767,0.655706,0.626372,0.761137,0.661089,0.751366,1000
27,Shared-comparison,Model 6: + all verified diet,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.770855,"{""model__C"": 1.0}",...,0.192192,0.736508,0.815064,0.518117,0.669235,0.651415,0.780250,0.664820,0.752853,1000
26,Shared-comparison,Model 3: Core KPIs + demographics,Regularized logistic regression,sleep_hours; resting_heart_rate; systolic_bp; ...,2713,0.329525,2170,543,0.769476,"{""model__C"": 1.0}",...,0.194897,0.732681,0.809534,0.502417,0.655397,0.637338,0.770953,0.659210,0.749350,1000

,comparison,model,estimator,starting_participant_count,participants_excluded_target_missing,predictor_availability_fraction_required,required_nonmissing_predictors,participants_excluded_predictor_availability_rule,participants_excluded_all_predictors_missing,participants_excluded_complete_case_rule,final_training_count,final_test_count,positive_outcome_count,negative_outcome_count
0,Complete-case,Model 0: Age only,Regularized logistic regression,6045,0,1.0,1,784,784,3332,2170,543,894,1819
1,Available-case,Model 0: Age only,Regularized logistic regression,6045,0,0.6,1,784,784,0,4208,1053,2310,2951
2,Complete-case,Model 1: Age + BMI,Regularized logistic regression,6045,0,1.0,2,872,8,3332,2170,543,894,1819
3,Available-case,Model 1: Age + BMI,Regularized logistic regression,6045,0,0.6,2,872,8,0,4138,1035,2267,2906
4,Complete-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,6045,0,1.0,3,1100,5,3332,2170,543,894,1819
5,Available-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,6045,0,0.6,2,79,5,0,4772,1194,2370,3596
6,Complete-case,Model 2: Core KPIs,Regularized logistic regression,6045,0,1.0,9,1195,4,3332,2170,543,894,1819
7,Available-case,Model 2: Core KPIs,Regularized logistic regression,6045,0,0.6,6,551,4,0,4395,1099,2325,3169
8,Complete-case,Model 3: Core KPIs + demographics,Regularized logistic regression,6045,0,1.0,12,1788,0,3332,2170,543,894,1819
9,Available-case,Model 3: Core KPIs + demographics,Regularized logistic regression,6045,0,0.6,8,571,0,0,4379,1095,2325,3149
10,Complete-case,Model 4: + diet nutrients,Regularized logistic regression,6045,0,1.0,23,2040,0,3332,2170,543,894,1819
11,Available-case,Model 4: + diet nutrients,Regularized logistic regression,6045,0,0.6,14,524,0,0,4416,1105,2154,3367
12,Complete-case,Model 5: + diet behaviours,Regularized logistic regression,6045,0,1.0,17,2701,0,3332,2170,543,894,1819
13,Available-case,Model 5: + diet behaviours,Regularized logistic regression,6045,0,0.6,11,236,0,0,4647,1162,2366,3443
14,Complete-case,Model 6: + all verified diet,Regularized logistic regression,6045,0,1.0,28,2878,0,3332,2170,543,894,1819
15,Available-case,Model 6: + all verified diet,Regularized logistic regression,6045,0,0.6,17,349,0,0,4556,1140,2234,3462
16,Complete-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,6045,0,1.0,13,2431,0,3332,2170,543,894,1819
17,Available-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,6045,0,0.6,8,127,0,0,4734,1184,2368,3550
18,Complete-case,Model 11: Full verified,Regularized logistic regression,6045,0,1.0,29,3332,0,3332,2170,543,894,1819
19,Available-case,Model 11: Full verified,Regularized logistic regression,6045,0,0.6,18,374,0,0,4536,1135,2209,3462
20,Complete-case,Model 12: Full without diet,Regularized logistic regression,6045,0,1.0,13,2431,0,3332,2170,543,894,1819
21,Available-case,Model 12: Full without diet,Regularized logistic regression,6045,0,0.6,8,127,0,0,4734,1184,2368,3550
22,Complete-case,Model 13: Full without family/proxy,Regularized logistic regression,6045,0,1.0,28,2878,0,3332,2170,543,894,1819
23,Available-case,Model 13: Full without family/proxy,Regularized logistic regression,6045,0,0.6,17,349,0,0,4556,1140,2234,3462
24,Complete-case,Model 14: Full with BMI only,Regularized logistic regression,6045,0,1.0,28,3332,0,3332,2170,543,894,1819
25,Available-case,Model 14: Full with BMI only,Regularized logistic regression,6045,0,0.6,17,373,0,0,4537,1135,2209,3463
26,Shared-comparison,Model 3: Core KPIs + demographics,Regularized logistic regression,6045,0,1.0,12,1788,0,0,2170,543,894,1819
27,Shared-comparison,Model 6: + all verified diet,Regularized logistic regression,6045,0,1.0,28,2878,0,0,2170,543,894,1819
28,Shared-comparison,Model 7P: + medical/family-risk proxy,Regularized logistic regression,6045,0,1.0,13,2431,0,0,2170,543,894,1819
29,Shared-comparison,Shared full: KPIs + demographics + diet + proxy,Regularized logistic regression,6045,0,1.0,29,3332,0,0,2170,543,894,1819
30,Complete-case,Model 11: Full verified,Random forest,6045,0,1.0,29,3332,0,3332,2170,543,894,1819
31,Complete-case,Model 11: Full verified,Gradient boosting,6045,0,1.0,29,3332,0,3332,2170,543,894,1819
32,Available-case,Model 11: Full verified,Random forest,6045,0,0.6,18,374,0,0,4536,1135,2209,3462
33,Available-case,Model 11: Full verified,Gradient boosting,6045,0,0.6,18,374,0,0,4536,1135,2209,3462

,audit_type,comparison,model,estimator,training_only_preprocessing,untouched_held_out_test_set,no_hba1c_or_diagnosis_leakage,same_participants_for_direct_comparison,comparison_partner,status
0,model,Complete-case,Model 0: Age only,Regularized logistic regression,True,True,True,NaN,,verified
1,model,Available-case,Model 0: Age only,Regularized logistic regression,True,True,True,NaN,,verified
2,model,Complete-case,Model 1: Age + BMI,Regularized logistic regression,True,True,True,NaN,,verified
3,model,Available-case,Model 1: Age + BMI,Regularized logistic regression,True,True,True,NaN,,verified
4,model,Complete-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,True,True,True,NaN,,verified
5,model,Available-case,Baseline 3: Age + BMI + systolic BP,Regularized logistic regression,True,True,True,NaN,,verified
6,model,Complete-case,Model 2: Core KPIs,Regularized logistic regression,True,True,True,NaN,,verified
7,model,Available-case,Model 2: Core KPIs,Regularized logistic regression,True,True,True,NaN,,verified
8,model,Complete-case,Model 3: Core KPIs + demographics,Regularized logistic regression,True,True,True,NaN,,verified
9,model,Available-case,Model 3: Core KPIs + demographics,Regularized logistic regression,True,True,True,NaN,,verified
10,model,Complete-case,Model 4: + diet nutrients,Regularized logistic regression,True,True,True,NaN,,verified
11,model,Available-case,Model 4: + diet nutrients,Regularized logistic regression,True,True,True,NaN,,verified
12,model,Complete-case,Model 5: + diet behaviours,Regularized logistic regression,True,True,True,NaN,,verified
13,model,Available-case,Model 5: + diet behaviours,Regularized logistic regression,True,True,True,NaN,,verified
14,model,Complete-case,Model 6: + all verified diet,Regularized logistic regression,True,True,True,NaN,,verified
15,model,Available-case,Model 6: + all verified diet,Regularized logistic regression,True,True,True,NaN,,verified
16,model,Complete-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,True,True,True,NaN,,verified
17,model,Available-case,Model 7P: + medical/family-risk proxy,Regularized logistic regression,True,True,True,NaN,,verified
18,model,Complete-case,Model 11: Full verified,Regularized logistic regression,True,True,True,NaN,,verified
19,model,Available-case,Model 11: Full verified,Regularized logistic regression,True,True,True,NaN,,verified
20,model,Complete-case,Model 12: Full without diet,Regularized logistic regression,True,True,True,NaN,,verified
21,model,Available-case,Model 12: Full without diet,Regularized logistic regression,True,True,True,NaN,,verified
22,model,Complete-case,Model 13: Full without family/proxy,Regularized logistic regression,True,True,True,NaN,,verified
23,model,Available-case,Model 13: Full without family/proxy,Regularized logistic regression,True,True,True,NaN,,verified
24,model,Complete-case,Model 14: Full with BMI only,Regularized logistic regression,True,True,True,NaN,,verified
25,model,Available-case,Model 14: Full with BMI only,Regularized logistic regression,True,True,True,NaN,,verified
26,model,Shared-comparison,Model 3: Core KPIs + demographics,Regularized logistic regression,True,True,True,NaN,,verified
27,model,Shared-comparison,Model 6: + all verified diet,Regularized logistic regression,True,True,True,NaN,,verified
28,model,Shared-comparison,Model 7P: + medical/family-risk proxy,Regularized logistic regression,True,True,True,NaN,,verified
29,model,Shared-comparison,Shared full: KPIs + demographics + diet + proxy,Regularized logistic regression,True,True,True,NaN,,verified
30,model,Complete-case,Model 11: Full verified,Random forest,True,True,True,NaN,,verified
31,model,Complete-case,Model 11: Full verified,Gradient boosting,True,True,True,NaN,,verified
32,model,Available-case,Model 11: Full verified,Random forest,True,True,True,NaN,,verified
33,model,Available-case,Model 11: Full verified,Gradient boosting,True,True,True,NaN,,verified
34,direct_incremental_comparison,Complete-case,Model 3: Core KPIs + demographics,Regularized logistic regression,True,True,True,True,Model 2: Core KPIs,verified
35,direct_incremental_comparison,Shared-comparison,Model 6: + all verified diet,Regularized logistic regression,True,True,True,True,Model 3: Core KPIs + demographics,verified
36,direct_incremental_comparison,Shared-comparison,Model 7P: + medical/family-risk proxy,Regularized logistic regression,True,True,True,True,Model 3: Core KPIs + demographics,verified
37,direct_incremental_comparison,Shared-comparison,Shared full: KPIs + demographics + diet + proxy,Regularized logistic regression,True,True,True,True,Model 3: Core KPIs + demographics,verified
38,direct_incremental_comparison,Complete-case,Model 11: Full verified,Regularized logistic regression,True,True,True,True,Model 1: Age + BMI,verified
39,direct_incremental_comparison,Complete-case,Model 11: Full verified,Regularized logistic regression,True,True,True,True,Model 14: Full with BMI only,verified

PASS: training-only pipelines, untouched tests, leakage controls, and paired participant checks verified.

## 7. Incremental predictive value

In [8]:
display(results["incremental"])
display(Markdown(
    "A feature group is not called meaningfully helpful when its gain is tiny "
    "or the paired bootstrap interval includes no improvement."
))

,comparison,comparison_cohort,base_model,expanded_model,held_out_participants,same_test_participants,delta_roc_auc,delta_pr_auc,delta_recall,delta_brier_score,delta_roc_auc_ci_lower,delta_roc_auc_ci_upper,delta_pr_auc_ci_lower,delta_pr_auc_ci_upper,delta_recall_ci_lower,delta_recall_ci_upper,delta_brier_score_ci_lower,delta_brier_score_ci_upper,interpretation
0,Add demographics,Complete-case,Model 2: Core KPIs,Model 3: Core KPIs + demographics,543,True,0.053671,0.068598,0.027933,-0.024164,0.021852,0.086388,0.013597,0.119994,-0.043223,0.095251,-0.035821,-1.273499e-02,Meaningful added predictive information
1,Add all verified diet,Shared-comparison,Model 3: Core KPIs + demographics,Model 6: + all verified diet,543,True,0.004574,0.013202,0.011173,-0.002706,-0.009080,0.017950,-0.008712,0.036739,-0.028417,0.052326,-0.007759,2.287694e-03,No clear meaningful improvement; gain is small...
2,Add medical/family-risk proxy,Shared-comparison,Model 3: Core KPIs + demographics,Model 7P: + medical/family-risk proxy,543,True,0.005326,0.004864,-0.011173,-0.002627,-0.001343,0.012248,-0.008408,0.016516,-0.047632,0.022867,-0.005413,-5.358740e-07,No clear meaningful improvement; gain is small...
3,Add all shared verified groups,Shared-comparison,Model 3: Core KPIs + demographics,Shared full: KPIs + demographics + diet + proxy,543,True,0.009147,0.015663,0.011173,-0.005569,-0.005071,0.024576,-0.008682,0.043117,-0.029078,0.051157,-0.011547,-2.685019e-04,No clear meaningful improvement; gain is small...
4,Full versus age + BMI,Complete-case,Model 1: Age + BMI,Model 11: Full verified,543,True,0.018786,0.025515,0.044693,-0.009546,-0.001781,0.038395,-0.010990,0.063016,-0.005718,0.091990,-0.017428,-1.651071e-03,No clear meaningful improvement; gain is small...
5,Add weight beyond BMI,Complete-case,Model 14: Full with BMI only,Model 11: Full verified,543,True,-0.002410,-0.007925,-0.005587,0.001087,-0.006962,0.002981,-0.017780,0.002780,-0.028257,0.017647,-0.000760,2.959916e-03,No clear meaningful improvement; gain is small...

A feature group is not called meaningfully helpful when its gain is tiny or the paired bootstrap interval includes no improvement.

## 8. Ablation analysis

In [9]:
display(results['ablation'])

,removed_group,status,removed_features,delta_roc_auc,delta_pr_auc,delta_recall,delta_brier_score
0,Diet nutrients,evaluated on same held-out participants,diet_calories; diet_carbohydrate_g; diet_total...,-0.002931,-0.010457,0.000000,0.002339
1,Diet behaviours,evaluated on same held-out participants,meals_away_from_home_7d; fast_food_meals_7d; r...,-0.001120,-0.000611,0.005587,0.000519
2,Family history,not available in full model,,NaN,NaN,NaN,NaN
3,Medical/family-risk proxy,evaluated on same held-out participants,medical_or_family_diabetes_risk,-0.004574,-0.002461,0.000000,0.002863
4,Smoking,not available in full model,,NaN,NaN,NaN,NaN
5,Food security,not available in full model,,NaN,NaN,NaN,NaN
6,Healthcare access,not available in full model,,NaN,NaN,NaN,NaN
7,Demographics,evaluated on same held-out participants,age; sex; income_context,-0.049850,-0.060064,0.000000,0.025147
8,Core KPIs,evaluated on same held-out participants,sleep_hours; resting_heart_rate; systolic_bp; ...,-0.017942,-0.049814,-0.039106,0.006255
9,Activity variables,evaluated on same held-out participants,vigorous_activity; moderate_activity; sedentar...,0.001596,-0.001490,0.000000,-0.000316
10,Sleep,evaluated on same held-out participants,sleep_hours,-0.006139,-0.009754,-0.011173,0.002932
11,Blood pressure,evaluated on same held-out participants,systolic_bp; diastolic_bp,-0.000153,0.002154,0.005587,-0.000418
12,BMI and weight,evaluated on same held-out participants,bmi; weight_kg,-0.008042,-0.029708,0.000000,0.002582

## 9. Family-specific analysis

In [10]:
display(results['family_analysis'])

,family_history_status,analysis_label,response,participant_count,elevated_hba1c_prevalence,warning,unadjusted_effect_scale,unadjusted_odds_ratio_yes_vs_no,unadjusted_ci_lower,unadjusted_ci_upper,adjusted_effect_scale,adjusted_odds_ratio_yes_vs_no,adjusted_ci_lower,adjusted_ci_upper,incremental_roc_auc,incremental_interpretation
0,Combined medical/family-risk proxy found,Reported medical or family-history diabetes risk,No,4359,0.295251,This is not genetics or pure family history.,Yes versus No,1.502052,1.290075,1.748859,Yes versus No,1.452188,1.214242,1.736763,0.005326,No clear meaningful improvement; gain is small...
1,Combined medical/family-risk proxy found,Reported medical or family-history diabetes risk,Yes,857,0.386231,This is not genetics or pure family history.,Yes versus No,1.502052,1.290075,1.748859,Yes versus No,1.452188,1.214242,1.736763,0.005326,No clear meaningful improvement; gain is small...

## 10. WellPath survey recommendations

In [11]:
display(results['recommendations'])

,Candidate survey field,NHANES source variable,Dataset evidence available,Incremental model value,Recommendation,Reason,Privacy or sensitivity concern,App usage,Limitation
0,Family history of diabetes,No direct universal variable,No,No clear meaningful improvement; gain is small...,Unavailable,Collect directly if desired; DIQ170 is combined.,Sensitive family medical information,Optional onboarding survey,Not evaluated directly in loaded NHANES files
1,Smoking status,SMQ_J absent,No,Not evaluated,Unavailable,Required source file was absent.,Sensitive health behaviour,Optional onboarding survey,No dataset evidence in this run
2,Fast-food frequency,DBD900,Yes,No clear meaningful improvement; gain is small...,Optional,Available but self-reported.,Low-to-moderate sensitivity,Optional context,Seven-day behaviour may vary
3,Meals away from home,DBD895,Yes,No clear meaningful improvement; gain is small...,Optional,Available but self-reported.,Low-to-moderate sensitivity,Optional context,Seven-day behaviour may vary
4,Food security,FSQ_J absent,No,Not evaluated,Unavailable,Required source file was absent.,High socioeconomic sensitivity,Optional survey only with clear purpose,No dataset evidence in this run
5,Healthcare access,HUQ_J absent,No,Not evaluated,Unavailable,Required source file was absent.,Sensitive access/insurance information,Optional survey,No dataset evidence in this run
6,Income context,INDFMPIR,Yes,Included with demographics,Optional,May add context but can proxy structural inequ...,High financial sensitivity,Avoid unless essential,Do not use punitively
7,Sleep,SLD012,Yes,Included in KPI models,Keep,Existing KPI and feasible to collect.,Health data,Monitoring signal,Self-report is imprecise
8,Activity,PAQ650; PAQ665; PAD680,Yes,Included in KPI models,Keep,Existing KPI group.,Health/behaviour data,Monitoring signal,Self-report is imprecise
9,Blood pressure,BPXSY1-3; BPXDI1-3,Yes,Included in KPI models,Keep,Objective examination KPI.,Health data,Monitoring signal,Single visit is not a diagnosis
10,Resting heart rate,BPXPLS,Yes,Included in KPI models,Keep,Objective examination KPI.,Health data,Monitoring signal,Single examination measure
11,BMI or weight,BMXBMI; BMXWT,Yes,Strong baseline contribution,Keep,Meaningful baseline predictors.,Sensitive body measurement,Monitoring signal,BMI does not measure body composition

## 11. Saved visualizations

In [12]:
chart_files = sorted((PROJECT_ROOT / "outputs" / "charts").glob("[01][0-9]_*.png"))
print(f"{len(chart_files)} expanded figures saved at 300 DPI:")
for chart in chart_files:
    print("-", chart.name)

16 expanded figures saved at 300 DPI:
- 01_roc_auc_by_feature_set.png
- 02_pr_auc_by_feature_set.png
- 03_recall_by_feature_set.png
- 04_brier_by_feature_set.png
- 05_incremental_auc_gain.png
- 06_incremental_recall_gain.png
- 07_ablation_auc_change.png
- 08_ablation_brier_change.png
- 09_full_logistic_exponentiated_coefficients.png
- 10_final_tree_permutation_importance.png
- 11_final_model_calibration.png
- 12_demonstration_confusion_matrix.png
- 13_diet_feature_missingness.png
- 14_family_history_decision.png
- 15_adjusted_diet_associations.png
- 16_model_sample_sizes.png

## 12. Plain-language result

In [13]:
diet_delta = summary["diet_delta_roc_auc"]
proxy_delta = summary["proxy_delta_roc_auc"]
full_delta = summary["full_vs_age_bmi_delta_roc_auc"]
weight_delta = summary["weight_beyond_bmi_delta_roc_auc"]
display(Markdown(f'''
1. **Outcome:** measured HbA1c at or above 5.7% versus below 5.7%; this is not a diabetes diagnosis.
2. **Cohorts:** strict complete-case n={summary["complete_case_sample_size"]:,}; shared-comparison n={summary["shared_comparison_sample_size"]:,}; full-model available-case n={summary["available_case_full_model_sample_size"]:,}, requiring at least {summary["available_case_min_predictor_fraction"]:.0%} of predictors before imputation.
3. **Existing KPIs:** sleep, resting pulse, blood pressure, BMI, weight, activity, and sedentary time.
4. **Diet:** 11 nutrient totals plus five verified diet behaviours were found.
5. **Family history:** no direct universal field was found. DIQ170 remains only a combined medical/family-risk proxy.
6. **Diet value:** ROC AUC changed by {diet_delta:+.3f} (95% CI {summary["diet_delta_roc_auc_ci_lower"]:+.3f} to {summary["diet_delta_roc_auc_ci_upper"]:+.3f}) on the shared test cohort. {summary["diet_incremental_result"]}.
7. **Proxy value:** ROC AUC changed by {proxy_delta:+.3f} (95% CI {summary["proxy_delta_roc_auc_ci_lower"]:+.3f} to {summary["proxy_delta_roc_auc_ci_upper"]:+.3f}). {summary["proxy_incremental_result"]}.
8. **Full versus age + BMI:** ROC AUC changed by {full_delta:+.3f} (95% CI {summary["full_vs_age_bmi_delta_roc_auc_ci_lower"]:+.3f} to {summary["full_vs_age_bmi_delta_roc_auc_ci_upper"]:+.3f}).
9. **Weight beyond BMI:** ROC AUC changed by {weight_delta:+.3f} (95% CI {summary["weight_beyond_bmi_delta_roc_auc_ci_lower"]:+.3f} to {summary["weight_beyond_bmi_delta_roc_auc_ci_upper"]:+.3f}). {summary["weight_beyond_bmi_result"]}.
10. **Smoking, food security, and healthcare access:** not evaluated because SMQ_J, FSQ_J, and HUQ_J were absent.
11. **Best complete-case model:** {summary["best_complete_case_model"]}, ROC AUC {summary["best_complete_case_roc_auc"]:.3f}.
12. **Best available-case model:** {summary["best_available_case_model"]}, ROC AUC {summary["best_available_case_roc_auc"]:.3f}.
13. **Safe claim:** exploratory cross-sectional associations and added predictive information in this dataset.
14. **Not safe to claim:** diagnosis, future diabetes prediction, causation, genetics, or clinical validation.
'''))

1. **Outcome:** measured HbA1c at or above 5.7% versus below 5.7%; this is not a diabetes diagnosis.
2. **Cohorts:** strict complete-case n=2,713; shared-comparison n=2,713; full-model available-case n=5,671, requiring at least 60% of predictors before imputation.
3. **Existing KPIs:** sleep, resting pulse, blood pressure, BMI, weight, activity, and sedentary time.
4. **Diet:** 11 nutrient totals plus five verified diet behaviours were found.
5. **Family history:** no direct universal field was found. DIQ170 remains only a combined medical/family-risk proxy.
6. **Diet value:** ROC AUC changed by +0.005 (95% CI -0.009 to +0.018) on the shared test cohort. No clear meaningful improvement; gain is small and/or uncertainty includes no improvement.
7. **Proxy value:** ROC AUC changed by +0.005 (95% CI -0.001 to +0.012). No clear meaningful improvement; gain is small and/or uncertainty includes no improvement.
8. **Full versus age + BMI:** ROC AUC changed by +0.019 (95% CI -0.002 to +0.038).
9. **Weight beyond BMI:** ROC AUC changed by -0.002 (95% CI -0.007 to +0.003). No clear meaningful improvement; gain is small and/or uncertainty includes no improvement.
10. **Smoking, food security, and healthcare access:** not evaluated because SMQ_J, FSQ_J, and HUQ_J were absent.
11. **Best complete-case model:** Model 14: Full with BMI only, ROC AUC 0.783.
12. **Best available-case model:** Model 6: + all verified diet, ROC AUC 0.804.
13. **Safe claim:** exploratory cross-sectional associations and added predictive information in this dataset.
14. **Not safe to claim:** diagnosis, future diabetes prediction, causation, genetics, or clinical validation.

## Reproducibility checklist

- All available XPT/CSV files were inspected.
- `SEQN` remains unique after joins.
- Day-one/day-two diet totals use the documented averaging rule.
- Family-history wording and skip patterns were reviewed.
- Leakage audit passed before training.
- Preprocessing remained inside training-fitted pipelines.
- Direct complete-case comparisons share test participants.
- 1,000-resample confidence intervals were generated.
- Tables, models, metadata, and separate 300-DPI charts were saved.
- The WellPath React/Vite applications were not used or modified.

**Research-use warning:** Associations are not causal effects. Optional survey
fields can be sensitive. This prototype is not clinically validated and must not
be used for diagnosis or medical decisions.
- The available-case 60% predictor-availability rule is reported before imputation.
- A dedicated shared cohort excludes unrelated optional groups.
- Medical/family-risk odds ratios use Yes versus No without standardizing the binary predictor.
- Weight beyond BMI is evaluated on identical held-out participants.
- `model_integrity_audit.csv` verifies training-only pipelines, disjoint tests,
  leakage controls, and participant matching for every direct comparison.